import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Feature from '../components/Feature'
import Maps from '../components/Maps'
import Feeds from '../components/Feeds'
import FacebookFeed from '../components/FacebookFeed'
import heroImage from '../image/her-bg-3.jpg'
import FeedCarousel from '../components/FeedCarousel'
import ScrollToTop from '../components/ScrollToTop'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tore City Next Js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* Hero */}
        <Hero
          title="Flytta till Töre!"
          description="Platsen där man väljer att leva"
          image={heroImage}
        />

        {/* feature */}
        <Feature />

        {/* Map */}
        <Maps />

        {/* Feeds */}
        <ScrollToTop/>
        <FacebookFeed />
        <FeedCarousel />
        {/* Hero */}
      </main>
    </>
  );
}
